Update links (#89)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,6 +63,15 @@ jobs:
       - name: "Run integration tests"
         run: xvfb-run -a npm run test-clean
 
+      - name: "Check package version"
+        if: github.event_name == 'pull_request'
+        run: |
+          git fetch origin main:main;
+          if diff <(git show main:package.json | jq -r .version) <(cat package.json | jq -r .version) > /dev/null; then \
+            echo "The package version is unchanged - attempts to publish this package would fail."; \
+            exit 1; \
+          fi
+
   publish:
     name: "Publish"
     runs-on: ubuntu-latest
